done
goitacademy/nodejs-homework-template pull request #3947
Opened 2023-09-06 10:16 UTC by Oleksii-co

2023-09-06 21:13 UTC, ceREAL133 requested changes
PR should go into your repo, not in goitacademy:master

2023-09-06 21:13 UTC, ceREAL133 commented on routes/api/contacts.js
> +  name: Joi.string().required(),
schema should be in separate file, you should validate email and phone properly

2023-09-06 21:13 UTC, ceREAL133 commented on routes/api/contacts.js
> +  try {
functions in router should be only invoked, not defined, separate them on another file

2023-09-06 21:13 UTC, ceREAL133 commented on routes/api/contacts.js
> +    //   res.status(status).json({
delete comments

2023-09-08 06:46 UTC, ceREAL133 requested changes

2023-09-08 06:46 UTC, ceREAL133 commented on schemas/contact.js
> +  name: Joi.string().required(),
add message to required

2023-09-12 19:37 UTC, Oleksii-co commented on schemas/contact.js
> +  name: Joi.string().required(),
Не зрозумів, Що потрібно добавити?

2023-09-14 10:30 UTC, closed without merging