Hw02 express
goitacademy/nodejs-homework-template pull request #4068
Opened 2023-09-17 18:10 UTC by Mykokola

2023-09-17 19:16 UTC, ceREAL133 requested changes

2023-09-17 19:16 UTC, ceREAL133 commented on untils/addContactSchema.js
у вас дві однакових схеми, навіщо?

2023-09-17 19:16 UTC, ceREAL133 commented on untils/updateContacatSchema.js
цю схему можна спокійно замінити першою

2023-09-18 03:06 UTC, closed without merging

2023-09-18 03:08 UTC, Mykokola commented on untils/updateContacatSchema.js
пеша схема що всі значення обовязкові
друга що може бути одне з перечислених значень якщо по тз